baseURL = "https://ismael.casimpan.com/quicktasks-git"
languageCode = "en-us"
title = "Quick Tasks: Git"
theme = "basics"

[params]
    author = "Ismael Casimpan"
    github = "icasimpan"
    #gitlab = "username2"
